spring:
  datasource:
    url: jdbc:h2:mem:mydb;MODE=PostgreSQL
    username: sa
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true
  liquibase.change-log: classpath:changeLogs/changeLog.xml